name: build-app

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - run: npm i
      - name: build
        run: npx nx build
      - name: archive
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: deploy_dist
          path: dist
